# Bot password for admin commands
admin_passwd: coolpass

server: irc.example.com
port: 6667
nick: Zombire
realname: Zombire
nspass: coolpass
# Be sure to put channel names inside quotes
channel: "#zombire"
# possible values for channel_access: xop, levels, flags
channel_accesstype: xop

# MySQL database information
db:
  host: localhost
  port: 3306
  user: zombire
  pass: coolpass
  database: zombiredb
