## Admin settings
# Bot password for admin commands
admin_passwd: coolpass

## IRC settings
server: irc.example.com
port: 6667
nick: Zombire
realname: Zombire
nspass: coolpass
# Be sure to put the channel name inside quotes
channel: "#zombire"
# possible values for channel_accesstype: xop, levels, flags
channel_accesstype: xop

## MySQL database settings
db:
  host: localhost
  port: 3306
  user: zombire
  pass: coolpass
  database: zombiredb
